import Link from "next/link";
import { ArrowRight, AtSign, BellRing, BookOpenCheck, CheckCircle2, Clock3, KeyRound, Link2, MessageCircleMore, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, Card } from "@/components/ui";
import { StatusBadge } from "@/components/status";
import { formatDate } from "@/lib/domain";
import { getConnection, listMedia } from "@/server/data";
import { env, isDemoMode } from "@/lib/env";

export const metadata = { title: "Integração" };

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ sync?: string; count?: string; error?: string; webhook?: string; comments?: string; found?: string; queued?: string; processed?: string; messages?: string; recovered?: string; token?: string }> }) {
  const query = await searchParams;
  const [connection, media] = await Promise.all([getConnection(), listMedia()]);
  return <div className="page-shell"><header className="page-header compact"><div><p className="eyebrow">Integração</p><h1>Conta do Instagram</h1><p>Estado da conexão, permissões e sincronização dos seus Reels.</p></div><Link className="button button-secondary" href="/connection-guide"><BookOpenCheck size={15} /> Ver guia completo <ArrowRight size={14} /></Link></header>
    {query.sync === "success" && <p className="form-success" role="status">Sincronização concluída. {Number(query.count ?? 0)} Reel(is) encontrado(s).</p>}
    {query.sync === "error" && <p className="form-alert" role="alert">A sincronização não foi concluída. Veja o motivo abaixo e tente novamente.</p>}
    {query.webhook === "active" && <p className="form-success" role="status">Webhook confirmado: a Meta já estava enviando comentários para o InstaChat.</p>}
    {query.webhook === "restored" && <p className="form-success" role="status">Webhook restaurado: a assinatura de comentários foi refeita com sucesso.</p>}
    {query.webhook === "error" && <p className="form-alert" role="alert">Não foi possível confirmar a assinatura do webhook. Reautorize o Instagram e tente novamente.</p>}
    {query.comments === "success" && <p className="form-success" role="status">Busca concluída: {Number(query.found ?? 0)} comentário(s) recente(s), {Number(query.queued ?? 0)} novo(s) na fila e {Number(query.processed ?? 0)} processado(s).</p>}
    {query.comments === "error" && <p className="form-alert" role="alert">Não foi possível buscar os comentários recentes pela API da Meta.</p>}
    {query.messages === "success" && <p className="form-success" role="status">Resposta recuperada: {Number(query.recovered ?? 0)} confirmação(ões) processada(s).</p>}
    {query.messages === "empty" && <p className="form-alert" role="status">Nenhuma nova resposta “pronto” foi encontrada nas conversas pendentes.</p>}
    {query.messages === "error" && <p className="form-alert" role="alert">Não foi possível consultar as respostas pendentes pela API da Meta.</p>}
    {query.token === "success" && <p className="form-success" role="status">Conexão renovada. O novo token de longa duração foi salvo com segurança.</p>}
    {query.token === "error" && <p className="form-alert" role="alert">A Meta não permitiu renovar este token. Se ele já expirou, reautorize o Instagram uma última vez.</p>}
    {query.error === "missing_basic" && <p className="form-alert" role="alert">A Meta conectou a conta, mas não concedeu a permissão <code>instagram_business_basic</code>. Adicione essa permissão no painel da Meta e reautorize.</p>}
    {query.error === "missing_comments" && <p className="form-alert" role="alert">A Meta conectou a conta, mas não concedeu a permissão <code>instagram_business_manage_comments</code>. Adicione essa permissão no painel da Meta e reautorize.</p>}
    {query.error === "missing_messages" && <p className="form-alert" role="alert">A Meta conectou a conta, mas não concedeu a permissão <code>instagram_business_manage_messages</code>. Adicione essa permissão no painel da Meta e reautorize.</p>}
    {connection ? <Card className="connection-card"><div className="connection-main"><div className="instagram-avatar"><AtSign size={24} /></div><div><div className="title-line"><h2>@{connection.username}</h2><StatusBadge status={connection.status} /></div><p>Conta profissional · Instagram API with Instagram Login</p></div></div><div className="connection-stats"><div><Clock3 size={16} /><span>Última sincronização<strong>{formatDate(connection.lastSyncAt)}</strong></span></div><div><CheckCircle2 size={16} /><span>Reels disponíveis<strong>{media.length}</strong></span></div><div><ShieldCheck size={16} /><span>Token válido até<strong>{formatDate(connection.tokenExpiresAt)}</strong></span></div></div><div className="connection-actions"><form action="/api/meta/media/sync" method="post"><Button variant="secondary" disabled={isDemoMode}><RefreshCw size={15} /> {isDemoMode ? "Simulação ativa" : "Sincronizar Reels"}</Button></form>{!isDemoMode && <form action="/api/meta/comments/sync" method="post"><Button variant="secondary"><MessageCircleMore size={15} /> Buscar comentários</Button></form>}{!isDemoMode && <form action="/api/meta/messages/sync" method="post"><Button variant="secondary"><MessageCircleMore size={15} /> Buscar respostas da DM</Button></form>}{!isDemoMode && <form action="/api/meta/webhook/subscription" method="post"><Button variant="secondary"><BellRing size={15} /> Verificar webhook</Button></form>}{!isDemoMode && <form action="/api/meta/token/refresh" method="post"><Button variant="secondary"><KeyRound size={15} /> Renovar conexão</Button></form>}{!isDemoMode && <a className="button button-primary" href="/api/meta/oauth/start"><Link2 size={15} /> Reautorizar Instagram</a>}</div></Card> : <Card className="empty-state"><AtSign size={28} /><h2>Conecte sua conta profissional</h2><p>O InstaChat solicitará acesso ao perfil, comentários e métricas de conteúdo.</p><a className="button button-primary" href="/api/meta/oauth/start">Conectar Instagram</a></Card>}
    {connection && <Card className="settings-info-card"><p className="eyebrow">Conexão persistente</p><h2>Renovação automática ativada</h2><p>O InstaChat usa um token de longa duração e tenta renová-lo diariamente quando faltarem 14 dias para vencer. Última renovação: <strong>{formatDate(connection.tokenRefreshedAt)}</strong>.</p><p>A Meta ainda pode invalidar o acesso se a senha mudar, a permissão for removida ou o aplicativo for revogado. Nesses casos, somente uma nova autorização resolve.</p></Card>}
    {connection?.lastError && <Card className="settings-info-card"><p className="eyebrow">Diagnóstico da última tentativa</p><h2>O que impediu a sincronização</h2><p>{connection.lastError}</p><p>Se a Meta mencionar permissão ou token, reautorize a conta pelo botão de conexão. Nenhum segredo é exibido nesta mensagem.</p></Card>}
    {!isDemoMode && <Card className="settings-info-card"><p className="eyebrow">Conferência do aplicativo Meta</p><h2>Client ID usado pelo InstaChat</h2><p><code>{env.META_APP_ID ?? "Não configurado"}</code></p><p>Esse número deve coincidir com o <strong>ID do app do Instagram</strong> do aplicativo atualmente conectado. Não use o ID principal exibido na URL do painel da Meta.</p></Card>}
    <Card className="permissions-card"><p className="eyebrow">Privilégio mínimo</p><h2>Permissões utilizadas</h2><div><code>instagram_business_basic</code><span>Identifica a conta e lista os Reels.</span></div><div><code>instagram_business_manage_comments</code><span>Recebe e responde comentários e autoriza a private reply.</span></div><div><code>instagram_business_manage_messages</code><span>Compatibilidade do envio privado pelo endpoint de mensagens da Meta.</span></div><div><code>instagram_business_manage_insights</code><span>Lê métricas dos Reels para contextualizar os sinais da audiência.</span></div></Card>
  </div>;
}
